import Link from "next/link";
import "./globals.css";
import Navbar from "./Navbar";

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang='en'>
			<body className='bg-gradient-to-r from-indigo-500 via-purple-500 to-pink-500'>
				<Navbar></Navbar>
				{children}
			</body>
		</html>
	);
}
